### ISSUE TITLE
Accessibility

### ISSUE THREAD

**Issue by ghost** [stem-discord/website#25]
Right now, if you go to [stem.help](https://stem.help) and tab through the links, there is no visual indication of which link you're focused on. Same thing if you go to [stem.help/meme](https://stem.help/meme) &mdash; this time, it shows if you're focused on the title input but not the others.

I tested this on Chrome and Firefox, if this matters at all.

I think that this isn't too hard to fix by setting `:focus-visible` in the CSS for links and input stuff, but I'm too ~~lazy~~ tired to look at the CSS and submit a PR for this right now.

**Comment by nopeless** [comment]
stem.help wi go through an overhaul
so i wont fix it
but i will keep it in mind
